### ISSUE TITLE
What is this issues?

### ISSUE THREAD

**Issue by KimHwaMok** [bbcmicrobit/micropython#386]
./tools/pyboard.py /dev/ttyACM0 examples/maze.py
Traceback (most recent call last):
  File "./tools/pyboard.py", line 327, in <module>
      main()
  File "./tools/pyboard.py", line 310, int main
      execbuffer(pyfile)
  File "./tools/pyboard.py", line 290, in execbuffer
      pyb = Pyboard(args.device[0], args.baudrate, args.user, args.password, args.wait)
  File "./tools/pyboard.py", line 125, in __init__
      import serial
ImportError: No module named serial

**Comment by dpgeorge** [comment]
You need to have pyserial installed: `pip install pyserial`
